-- Örnek: merkez_db kiracı başına Logo REST URL
-- Tam script: database/scripts/merkez_tenant_registry_logo_rest_default.sql
-- UPDATE public.tenant_registry SET logo_rest_api_url = 'http://185.206.80.132:32001/api/v1', updated_at = now() WHERE code = 'kasap';
