import { DEFAULT_SAAS_TENANT_POSTGREST_ORIGIN } from '../../../services/merkezTenantRegistry';
import type { SetupAppConfig } from './setupTypes';

/** Kurulum sihirbazı başlangıç yapılandırması — Rust AppConfig ile uyumlu db_mode / provider. */
export function createInitialSetupConfig(): SetupAppConfig {
  return {
    is_configured: false,
    db_mode: 'hybrid',
    local_db: 'localhost:5432/retailex_local',
    remote_db: '',
    connection_provider: 'rest_api',
    remote_rest_url: DEFAULT_SAAS_TENANT_POSTGREST_ORIGIN,
    hybrid_read_preference: 'local_first',
    hybrid_sync_direction: 'local_to_remote',
    hybrid_sync_interval_sec: 30,
    hybrid_sync_transport: 'both',
    terminal_name: 'TERMINAL-01',
    store_id: '',
    erp_firm_nr: '001',
    erp_period_nr: '01',
    erp_method: 'sql',
    erp_host: '26.154.3.237',
    erp_user: 'sa',
    erp_pass: 'r9hWP3oJoC7cTfr',
    erp_db: 'LOGO',
    title: 'RetailEx OS',
    pg_local_user: 'postgres',
    pg_local_pass: 'Yq7xwQpt6c',
    pg_remote_user: '',
    pg_remote_pass: '',
    skip_integration: false,
    system_type: 'retail',
    role: 'client',
    central_api_url: '',
    central_ws_url: '',
    selected_firms: [],
    device_id: '',
    logo_objects_user: '',
    logo_objects_pass: '',
    logo_objects_path: 'C:\\LOGO\\LObjects.dll',
    logo_objects_active: false,
    backup_config: {
      enabled: true,
      daily_backup: true,
      hourly_backup: false,
      periodic_min: 0,
      backup_path: 'C:\\RetailEx_Backups',
      last_run: '',
    },
    selected_cash_registers: [],
    is_nebim_migration: false,
    enabled_modules: ['pos', 'wms'],
    bayi_seti: false,
    default_currency: 'IQD',
    regulatory_region: 'IQ',
  };
}
