/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fvancybedqhwhzqwpass"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2YW5jeWJlZHFod2h6cXdwYXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MjE4OTAsImV4cCI6MjA4MTM5Nzg5MH0._npAbJBFNbgqEUo2fv3p_0is5nObYiGASKKN-L7iEqU"

